# Generated by Django 4.2.7 on 2023-12-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('views_count', models.IntegerField(default=0, verbose_name='просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
    ]
